version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prismaconnection
      POSTGRES_PASSWORD: y@YmkxBJ9hu4Q!EU
      POSTGRES_DB: barberdb
    # restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
  backend:
    image: adautovjr/barber-app:latest
    ports:
      - "8081:3000"
